framework:
    workflows:
        cargo_request:
#            audit_trail:
#                enabled: true
            type: state_machine # or workflow state_machine
            supports:
                - App\Entity\CargoRequest
            marking_store:
                type: method
                property: status
            initial_marking: !php/const App\Workflow\CargoRequestTransitions::STATUS_APPROVED
            places:
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_SUBMITTED
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_APPROVED
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_LOCK_CARGO_REQUEST
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_DECLINED_OWNER
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_DECLINED_EXECUTOR
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_EXECUTED
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_EXECUTED_CONFIRMATION
                - !php/const App\Workflow\CargoRequestTransitions::STATUS_REJECTED_EXECUTION
            transitions:
                test:
                    from: !php/const App\Workflow\CargoRequestTransitions::STATUS_APPROVED
                    to: !php/const App\Workflow\CargoRequestTransitions::STATUS_SUBMITTED
#                submitted:
#                    from: submitted
#                    to: [ !php/const App\Workflow\CargoRequestTransitions::STATUS_APPROVED, !php/const App\Workflow\CargoRequestTransitions::STATUS_REJECTED_EXECUTION ]
#                approved:
#                    from: !php/const App\Workflow\CargoRequestTransitions::STATUS_APPROVED
#                    to: [!php/const App\Workflow\CargoRequestTransitions::STATUS_LOCK_CARGO_REQUEST, !php/const App\Workflow\CargoRequestTransitions::STATUS_DECLINED_OWNER]
#                rejected_sys:
#                    from: rejected_sys
#                    to:
#                executed_executor:
#                    from: approved
#                    to: executed
#                    guard: 'executor'
#                execution_rejected:
#                    from: executed
#                    to: [execution_confirmed, execution_rejected]
#                    guard: 'owner'
#                close:
#                    from: approved
#                    to: execution_confirmed
#                    guard: 'owner'
